# steps:
#   - name: 'gcr.io/cloud-builders/docker'
#     id: 'build-image'
#     args:
#       - 'build'
#       - '-t'
#       - 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
#       - '-t'
#       - 'gcr.io/$PROJECT_ID/himas-training:latest'
#       - '-f'
#       - 'PoC/Model-Pipeline/himas-model-pipeline/Dockerfile'
#       - 'PoC/Model-Pipeline/himas-model-pipeline/'

#   - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
#     id: 'train-model'
#     env:
#       - 'GCP_PROJECT_ID=$PROJECT_ID'
#       - 'DATASET_ID=federated_demo'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         cp -r /workspace/PoC/Model-Pipeline/himas-model-pipeline/* /app/
#         cd /app
#         echo "Starting training with federated_demo..."
#         flwr run .
#         mkdir -p /workspace/models
#         cp models/himas_federated_mortality_model.keras /workspace/models/
#         ls -lh /workspace/models/

#   - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
#     id: 'evaluate-model'
#     env:
#       - 'GCP_PROJECT_ID=$PROJECT_ID'
#       - 'DATASET_ID=federated_demo'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         cp -r /workspace/PoC/Model-Pipeline/himas-model-pipeline/* /app/
#         cd /app
#         mkdir -p models
#         cp /workspace/models/himas_federated_mortality_model.keras models/
#         mkdir -p evaluation_results
#         python evaluate_model.py
#         cp -r evaluation_results /workspace/

#   - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
#     id: 'validate-metrics'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         cd /workspace
#         ACC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .accuracy' evaluation_results/*.json)
#         REC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .recall' evaluation_results/*.json)
#         echo "Accuracy: $$ACC | Recall: $$REC"
#         if (( $$(echo "$$ACC < 0.85" | bc -l) )); then
#           exit 1
#         fi
#         if (( $$(echo "$$REC < 0.60" | bc -l) )); then
#           exit 1
#         fi
#         echo "Metrics passed"

#   - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
#     id: 'bias-detection'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         cd /workspace
#         AGG_ACC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .accuracy' evaluation_results/*.json)
#         AGG_REC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .recall' evaluation_results/*.json)
#         BIAS=false
#         for h in hospital_a hospital_b hospital_c; do
#           A=$$(jq ".[] | select(.hospital==\"$$h\") | .accuracy" evaluation_results/*.json)
#           R=$$(jq ".[] | select(.hospital==\"$$h\") | .recall" evaluation_results/*.json)
#           AD=$$(echo "$$AGG_ACC - $$A" | bc -l | awk '{if($$1<0)print -$$1; else print $$1}')
#           RD=$$(echo "$$AGG_REC - $$R" | bc -l | awk '{if($$1<0)print -$$1; else print $$1}')
#           if (( $$(echo "$$AD > 0.05" | bc -l) )) || (( $$(echo "$$RD > 0.07" | bc -l) )); then
#             BIAS=true
#           fi
#         done
#         if [ "$$BIAS" = true ]; then
#           exit 1
#         fi
#         echo "No bias detected"

#   - name: 'gcr.io/cloud-builders/gsutil'
#     id: 'upload-model'
#     args:
#       - 'cp'
#       - '/workspace/models/himas_federated_mortality_model.keras'
#       - 'gs://himas-mlops-models/models/model_$BUILD_ID.keras'

#   - name: 'gcr.io/cloud-builders/gsutil'
#     id: 'upload-results'
#     args:
#       - '-m'
#       - 'cp'
#       - '-r'
#       - '/workspace/evaluation_results/'
#       - 'gs://himas-mlops-models/evaluation-results/$BUILD_ID/'

# images:
#   - 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
#   - 'gcr.io/$PROJECT_ID/himas-training:latest'

# options:
#   machineType: 'E2_HIGHCPU_8'
#   logging: CLOUD_LOGGING_ONLY

# timeout: '3600s'

#change made2
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/himas-training:latest'
      - '-f'
      - 'PoC/Model-Pipeline/himas-model-pipeline/Dockerfile'
      - 'PoC/Model-Pipeline/himas-model-pipeline/'

  - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
    id: 'train-model'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      - 'DATASET_ID=federated_demo'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp -r /workspace/PoC/Model-Pipeline/himas-model-pipeline/* /app/
        cd /app
        echo "Starting training with federated_demo..."
        flwr run .
        mkdir -p /workspace/models
        cp models/himas_federated_mortality_model.keras /workspace/models/
        ls -lh /workspace/models/

  - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
    id: 'evaluate-model'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      - 'DATASET_ID=federated_demo'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp -r /workspace/PoC/Model-Pipeline/himas-model-pipeline/* /app/
        cd /app
        mkdir -p models
        cp /workspace/models/himas_federated_mortality_model.keras models/
        mkdir -p evaluation_results
        python evaluate_model.py
        cp -r evaluation_results /workspace/

  - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
    id: 'validate-metrics'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace
        ACC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .accuracy' evaluation_results/*.json)
        REC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .recall' evaluation_results/*.json)
        echo "Accuracy: $$ACC | Recall: $$REC"
        if (( $$(echo "$$ACC < 0.85" | bc -l) )); then
          exit 1
        fi
        if (( $$(echo "$$REC < 0.60" | bc -l) )); then
          exit 1
        fi
        echo "Metrics passed"

  - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
    id: 'bias-detection'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp -r /workspace/PoC/Model-Pipeline/himas-model-pipeline/* /app/
        cd /app
        cp -r /workspace/evaluation_results .
        python bias_detection.py

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-model'
    args:
      - 'cp'
      - '/workspace/models/himas_federated_mortality_model.keras'
      - 'gs://himas-mlops-models/models/model_$BUILD_ID.keras'

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-results'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - '/workspace/evaluation_results/'
      - 'gs://himas-mlops-models/evaluation-results/$BUILD_ID/'

  - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
    id: 'register-model-vertex'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Extract metrics from evaluation results
        cd /workspace
        ACC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .accuracy' evaluation_results/*.json)
        REC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .recall' evaluation_results/*.json)
        PREC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .precision' evaluation_results/*.json)
        
        echo "Registering model in Vertex AI Model Registry..."
        echo "Accuracy: $$ACC | Recall: $$REC | Precision: $$PREC"
        
        # Register model in Vertex AI Model Registry
        gcloud ai models upload \
          --region=us-central1 \
          --display-name=himas-federated-mortality-model \
          --description="Federated learning model for ICU mortality prediction - Build $BUILD_ID" \
          --artifact-uri=gs://himas-mlops-models/models/model_$BUILD_ID.keras \
          --container-image-uri=gcr.io/$PROJECT_ID/himas-training:$BUILD_ID \
          --version-aliases=build-$BUILD_ID,latest \
          --project=$PROJECT_ID
        
        echo "✅ Model registered in Vertex AI Model Registry"


images:
  - 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/himas-training:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '3600s'