# steps:
#   - name: 'gcr.io/cloud-builders/docker'
#     id: 'build-image'
#     args:
#       - 'build'
#       - '-t'
#       - 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
#       - '-t'
#       - 'gcr.io/$PROJECT_ID/himas-training:latest'
#       - '-f'
#       - 'PoC/Model-Pipeline/himas-model-pipeline/Dockerfile'
#       - 'PoC/Model-Pipeline/himas-model-pipeline/'

#   - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
#     id: 'train-model'
#     env:
#       - 'GCP_PROJECT_ID=$PROJECT_ID'
#       - 'DATASET_ID=federated_demo'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         cp -r /workspace/PoC/Model-Pipeline/himas-model-pipeline/* /app/
#         cd /app
#         echo "Starting training with federated_demo..."
#         flwr run .
#         mkdir -p /workspace/models
#         cp models/himas_federated_mortality_model.keras /workspace/models/
#         ls -lh /workspace/models/

#   - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
#     id: 'evaluate-model'
#     env:
#       - 'GCP_PROJECT_ID=$PROJECT_ID'
#       - 'DATASET_ID=federated_demo'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         cp -r /workspace/PoC/Model-Pipeline/himas-model-pipeline/* /app/
#         cd /app
#         mkdir -p models
#         cp /workspace/models/himas_federated_mortality_model.keras models/
#         mkdir -p evaluation_results
#         python evaluate_model.py
#         cp -r evaluation_results /workspace/

#   - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
#     id: 'validate-metrics'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         cd /workspace
#         ACC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .accuracy' evaluation_results/*.json)
#         REC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .recall' evaluation_results/*.json)
#         echo "Accuracy: $$ACC | Recall: $$REC"
#         if (( $$(echo "$$ACC < 0.85" | bc -l) )); then
#           exit 1
#         fi
#         if (( $$(echo "$$REC < 0.60" | bc -l) )); then
#           exit 1
#         fi
#         echo "Metrics passed"

#   - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
#     id: 'bias-detection'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         cd /workspace
#         AGG_ACC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .accuracy' evaluation_results/*.json)
#         AGG_REC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .recall' evaluation_results/*.json)
#         BIAS=false
#         for h in hospital_a hospital_b hospital_c; do
#           A=$$(jq ".[] | select(.hospital==\"$$h\") | .accuracy" evaluation_results/*.json)
#           R=$$(jq ".[] | select(.hospital==\"$$h\") | .recall" evaluation_results/*.json)
#           AD=$$(echo "$$AGG_ACC - $$A" | bc -l | awk '{if($$1<0)print -$$1; else print $$1}')
#           RD=$$(echo "$$AGG_REC - $$R" | bc -l | awk '{if($$1<0)print -$$1; else print $$1}')
#           if (( $$(echo "$$AD > 0.05" | bc -l) )) || (( $$(echo "$$RD > 0.07" | bc -l) )); then
#             BIAS=true
#           fi
#         done
#         if [ "$$BIAS" = true ]; then
#           exit 1
#         fi
#         echo "No bias detected"

#   - name: 'gcr.io/cloud-builders/gsutil'
#     id: 'upload-model'
#     args:
#       - 'cp'
#       - '/workspace/models/himas_federated_mortality_model.keras'
#       - 'gs://himas-mlops-models/models/model_$BUILD_ID.keras'

#   - name: 'gcr.io/cloud-builders/gsutil'
#     id: 'upload-results'
#     args:
#       - '-m'
#       - 'cp'
#       - '-r'
#       - '/workspace/evaluation_results/'
#       - 'gs://himas-mlops-models/evaluation-results/$BUILD_ID/'

# images:
#   - 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
#   - 'gcr.io/$PROJECT_ID/himas-training:latest'

# options:
#   machineType: 'E2_HIGHCPU_8'
#   logging: CLOUD_LOGGING_ONLY

# timeout: '3600s'

#change made2
steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/himas-training:latest'
      - '-f'
      - 'PoC/Model-Pipeline/himas-model-pipeline/Dockerfile'
      - 'PoC/Model-Pipeline/himas-model-pipeline/'

  - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
    id: 'train-model'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      - 'DATASET_ID=federated_demo'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp -r /workspace/PoC/Model-Pipeline/himas-model-pipeline/* /app/
        cd /app
        echo "Starting training with federated_demo..."
        flwr run .
        mkdir -p /workspace/models
        
        # Find the model file wherever it was saved
        MODEL_FILE=$$(find models -name "*.keras" -type f | head -1)
        
        if [ -z "$$MODEL_FILE" ]; then
          echo "❌ No model file found!"
          ls -lR models/
          exit 1
        fi
        
        echo "✅ Found model: $$MODEL_FILE"
        cp $$MODEL_FILE /workspace/models/himas_federated_mortality_model.keras
        echo "✅ Model copied to workspace:"
        ls -lh /workspace/models/

  - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
    id: 'evaluate-model'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      - 'DATASET_ID=federated_demo'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp -r /workspace/PoC/Model-Pipeline/himas-model-pipeline/* /app/
        cd /app
        mkdir -p models
        cp /workspace/models/himas_federated_mortality_model.keras models/
        mkdir -p evaluation_results
        python scripts/evaluate_model.py
        cp -r evaluation_results /workspace/

  - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
    id: 'validate-metrics'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace
        ACC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .accuracy' evaluation_results/*.json)
        REC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .recall' evaluation_results/*.json)
        echo "Accuracy: $$ACC | Recall: $$REC"
        if (( $$(echo "$$ACC < 0.85" | bc -l) )); then
          exit 1
        fi
        if (( $$(echo "$$REC < 0.60" | bc -l) )); then
          exit 1
        fi
        echo "Metrics passed"

  # - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
  #   id: 'bias-detection'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       cp -r /workspace/PoC/Model-Pipeline/himas-model-pipeline/* /app/
  #       cd /app
  #       cp -r /workspace/evaluation_results .
  #       python bias_detection.py

  - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
    id: 'compare-with-previous'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace
        
        echo "Checking for previous model..."
        
        # Get current model metrics
        NEW_ACC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .accuracy' evaluation_results/*.json)
        NEW_REC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .recall' evaluation_results/*.json)
        
        echo "New model - Accuracy: $$NEW_ACC, Recall: $$NEW_REC"
        
        # Try to get the latest previous model from GCS
        PREV_BUILD=$$(gsutil ls gs://himas-mlops-models/evaluation-results/ | sort -r | sed -n '2p' | xargs basename)
        
        if [ -z "$$PREV_BUILD" ]; then
          echo "No previous model found. This is the first model - proceeding."
          exit 0
        fi
        
        echo "Found previous build: $$PREV_BUILD"
        
        # Download previous model's metrics
        mkdir -p prev_results
        gsutil cp gs://himas-mlops-models/evaluation-results/$$PREV_BUILD/*.json prev_results/ || {
          echo "Could not fetch previous results. Proceeding with current model."
          exit 0
        }
        
        # Get previous model metrics
        PREV_ACC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .accuracy' prev_results/*.json)
        PREV_REC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .recall' prev_results/*.json)
        
        echo "Previous model - Accuracy: $$PREV_ACC, Recall: $$PREV_REC"
        
        # Compare models (new model must be better OR within 2% tolerance)
        ACC_DIFF=$$(echo "$$NEW_ACC - $$PREV_ACC" | bc -l)
        REC_DIFF=$$(echo "$$NEW_REC - $$PREV_REC" | bc -l)
        
        echo "Accuracy difference: $$ACC_DIFF"
        echo "Recall difference: $$REC_DIFF"
        
        # Rollback if new model is significantly worse (>2% drop in either metric)
        if (( $$(echo "$$ACC_DIFF < -0.02" | bc -l) )) || (( $$(echo "$$REC_DIFF < -0.02" | bc -l) )); then
          echo "❌ ROLLBACK: New model performs worse than previous model"
          echo "   Previous: Acc=$$PREV_ACC, Rec=$$PREV_REC"
          echo "   New:      Acc=$$NEW_ACC, Rec=$$NEW_REC"
          echo "   Not uploading new model."
          exit 1
        else
          echo "✅ New model is better or comparable. Proceeding with upload."
          exit 0
        fi

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-model'
    args:
      - 'cp'
      - '/workspace/models/himas_federated_mortality_model.keras'
      - 'gs://himas-mlops-models/models/model_$BUILD_ID.keras'

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-results'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - '/workspace/evaluation_results/'
      - 'gs://himas-mlops-models/evaluation-results/$BUILD_ID/'

  - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
    id: 'register-model-vertex'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Extract metrics from evaluation results
        cd /workspace
        ACC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .accuracy' evaluation_results/*.json)
        REC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .recall' evaluation_results/*.json)
        PREC=$$(jq '.[] | select(.hospital=="AGGREGATED") | .precision' evaluation_results/*.json)
        
        echo "Registering model in Vertex AI Model Registry..."
        echo "Accuracy: $$ACC | Recall: $$REC | Precision: $$PREC"
        
        # Register model in Vertex AI Model Registry
        gcloud ai models upload \
          --region=us-central1 \
          --display-name=himas-federated-mortality-model \
          --description="Federated learning model for ICU mortality prediction - Build $BUILD_ID" \
          --artifact-uri=gs://himas-mlops-models/models/model_$BUILD_ID.keras \
          --container-image-uri=gcr.io/$PROJECT_ID/himas-training:$BUILD_ID \
          --version-aliases=build-$BUILD_ID,latest \
          --project=$PROJECT_ID
        
        echo "✅ Model registered in Vertex AI Model Registry"


images:
  - 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/himas-training:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '3600s'