steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/himas-training:latest'
      - '-f'
      - 'PoC/Model-Pipeline/himas-model-pipeline/Dockerfile'
      - 'PoC/Model-Pipeline/himas-model-pipeline/'

  - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
    id: 'train-model'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      - 'DATASET_ID=federated_demo'
      - 'MLFLOW_TRACKING_URI=file:///workspace/mlruns'
      - 'MLFLOW_EXPERIMENT_NAME=himas-federated-training'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp -r /workspace/PoC/Model-Pipeline/himas-model-pipeline/* /app/
        cd /app
        echo "Starting training with federated_demo..."
        flwr run .
        mkdir -p /workspace/models
        
        # Find the model file wherever it was saved
        MODEL_FILE=$$(find models -name "*.keras" -type f | head -1)
        
        if [ -z "$$MODEL_FILE" ]; then
          echo "❌ No model file found!"
          ls -lR models/
          exit 1
        fi
        
        echo "✅ Found model: $$MODEL_FILE"
        cp $$MODEL_FILE /workspace/models/himas_federated_mortality_model.keras
        echo "✅ Model copied to workspace:"
        ls -lh /workspace/models/

  - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
    id: 'evaluate-model'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      - 'DATASET_ID=federated_demo'
      - 'MLFLOW_TRACKING_URI=file:///workspace/mlruns'
      - 'MLFLOW_EXPERIMENT_NAME=himas-federated-eval'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp -r /workspace/PoC/Model-Pipeline/himas-model-pipeline/* /app/
        cd /app
        mkdir -p models
        cp /workspace/models/himas_federated_mortality_model.keras models/

        cp -r /workspace/mlruns /app/ || echo "No mlruns from training"
        
        rm -rf evaluation_results
        mkdir -p evaluation_results
        python scripts/evaluate_model.py
        cp -r evaluation_results /workspace/

        cp -r /app/mlruns /workspace/ || echo "No mlruns folder found"

  - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
    id: 'validate-metrics'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace
        LATEST_JSON=$$(ls -t evaluation_results/results/*.json | head -1)
        echo "Using metrics from: $$LATEST_JSON"
        ACC=$$(jq '.metrics_by_hospital[] | select(.hospital=="AGGREGATED") | .accuracy' $$LATEST_JSON)
        REC=$$(jq '.metrics_by_hospital[] | select(.hospital=="AGGREGATED") | .recall' $$LATEST_JSON)
        echo "Accuracy: $$ACC | Recall: $$REC"
        if (( $$(echo "$$ACC < 0.85" | bc -l) )); then
          exit 1
        fi
        if (( $$(echo "$$REC < 0.60" | bc -l) )); then
          exit 1
        fi
        echo "Metrics passed"

  - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
    id: 'bias-detection'
    env:
      - 'GCP_PROJECT_ID=$PROJECT_ID'
      - 'DATASET_ID=federated_demo'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        cp -r /workspace/PoC/Model-Pipeline/himas-model-pipeline/* /app/
        cd /app
        
        # Copy trained model
        mkdir -p models
        cp /workspace/models/himas_federated_mortality_model.keras models/
        
        echo "Running bias detection..."
        
        # Step 1: Detect bias and generate bias_summary.json
        python bias_detection/detect_bias.py \
          --model-path models/himas_federated_mortality_model.keras \
          --threshold 0.5 \
          --dp-threshold 0.1 \
          --eo-threshold 0.1 \
          --output-dir bias_detection_results
        
        # Step 2: Check if bias passes threshold (CI/CD gate)
        python bias_detection/bias_checker.py \
          --bias-summary bias_detection_results/reports/bias_summary.json \
          --threshold-demographic-parity 0.1 \
          --threshold-equalized-odds 0.1
        
        echo "✅ Bias detection complete"
        
        # Copy results to workspace for upload
        cp -r bias_detection_results /workspace/

  - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
    id: 'compare-with-previous'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace
        
        echo "Checking for previous model..."
        
        LATEST_JSON=$$(ls -t evaluation_results/results/*.json | head -1)

        echo "Using metrics from: $$LATEST_JSON"

        NEW_ACC=$$(jq '.metrics_by_hospital[] | select(.hospital=="AGGREGATED") | .accuracy' $$LATEST_JSON)
        NEW_REC=$$(jq '.metrics_by_hospital[] | select(.hospital=="AGGREGATED") | .recall' $$LATEST_JSON)

        echo "New model - Accuracy: $$NEW_ACC, Recall: $$NEW_REC"
        
        # Try to get the latest previous model from GCS
        PREV_BUILD=$$(gsutil ls gs://himas-mlops-models/evaluation-results/ | sort -r | sed -n '2p' | xargs basename)
        
        if [ -z "$$PREV_BUILD" ]; then
          echo "No previous model found. This is the first model - proceeding."
          exit 0
        fi
        
        echo "Found previous build: $$PREV_BUILD"
        
        # Download previous model's metrics
        mkdir -p prev_results
        gsutil cp gs://himas-mlops-models/evaluation-results/$$PREV_BUILD/*.json prev_results/ || {
          echo "Could not fetch previous results. Proceeding with current model."
          exit 0
        }
        PREV_LATEST=$$(ls -t prev_results/*.json | head -1)
        # Get previous model metrics
        PREV_ACC=$$(jq '.metrics_by_hospital[] | select(.hospital=="AGGREGATED") | .accuracy' $$PREV_LATEST)
        PREV_REC=$$(jq '.metrics_by_hospital[] | select(.hospital=="AGGREGATED") | .recall' $$PREV_LATEST)
        
        echo "Previous model - Accuracy: $$PREV_ACC, Recall: $$PREV_REC"
        
        # Compare models (new model must be better OR within 2% tolerance)
        ACC_DIFF=$$(echo "$$NEW_ACC - $$PREV_ACC" | bc -l)
        REC_DIFF=$$(echo "$$NEW_REC - $$PREV_REC" | bc -l)
        
        echo "Accuracy difference: $$ACC_DIFF"
        echo "Recall difference: $$REC_DIFF"
        
        # Rollback if new model is significantly worse (>2% drop in either metric)
        if (( $$(echo "$$ACC_DIFF < -0.02" | bc -l) )) || (( $$(echo "$$REC_DIFF < -0.02" | bc -l) )); then
          echo "❌ ROLLBACK: New model performs worse than previous model"
          echo "   Previous: Acc=$$PREV_ACC, Rec=$$PREV_REC"
          echo "   New:      Acc=$$NEW_ACC, Rec=$$NEW_REC"
          echo "   Not uploading new model."
          exit 1
        else
          echo "✅ New model is better or comparable. Proceeding with upload."
          exit 0
        fi
#
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-model'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TIMESTAMP=$$(date +%Y%m%d_%H%M%S)
        echo "Uploading model with timestamp: $$TIMESTAMP"
        gsutil cp /workspace/models/himas_federated_mortality_model.keras \
          gs://himas-mlops-models/models/$${TIMESTAMP}_$BUILD_ID/model.keras
        
        # Store timestamp for next step
        echo "$$TIMESTAMP" > /workspace/model_timestamp.txt
      

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-results'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - '/workspace/evaluation_results/'
      - 'gs://himas-mlops-models/evaluation-results/$BUILD_ID/'

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-mlflow-artifacts'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - '/workspace/mlruns'
      - 'gs://himas-mlops-models/mlflow-runs/$BUILD_ID/'

  - name: 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
    id: 'register-model-in-registry'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace
        
        # Read timestamp
        TIMESTAMP=$$(cat /workspace/model_timestamp.txt)
        echo "Using timestamp: $$TIMESTAMP"

        # Get metrics
        LATEST_JSON=$$(ls -t evaluation_results/results/*.json | head -1)
        ACC=$$(jq '.metrics_by_hospital[] | select(.hospital=="AGGREGATED") | .accuracy' $$LATEST_JSON)
        REC=$$(jq '.metrics_by_hospital[] | select(.hospital=="AGGREGATED") | .recall' $$LATEST_JSON)
        PREC=$$(jq '.metrics_by_hospital[] | select(.hospital=="AGGREGATED") | .precision' $$LATEST_JSON)
        F1=$$(jq '.metrics_by_hospital[] | select(.hospital=="AGGREGATED") | .f1_score' $$LATEST_JSON)
        AUC=$$(jq '.metrics_by_hospital[] | select(.hospital=="AGGREGATED") | .roc_auc' $$LATEST_JSON)
        
        echo "Registering model in Model Registry..."
        echo "Metrics - Accuracy: $$ACC | Recall: $$REC | Precision: $$PREC"
        
        # Create model registry entry (model card)
        cat > model_card.json <<EOF
        {
          "model_info": {
            "name": "himas-federated-mortality-model",
            "version": "$BUILD_ID",
            "timestamp": "$$TIMESTAMP",
            "status": "production",
            "registered_at": "$$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          },
          "artifacts": {
            "model_file": "gs://himas-mlops-models/models/$${TIMESTAMP}_$BUILD_ID/model.keras",
            "container_image": "gcr.io/$PROJECT_ID/himas-training:$BUILD_ID",
            "evaluation_results": "gs://himas-mlops-models/evaluation-results/$BUILD_ID/",
            "mlflow_tracking": "gs://himas-mlops-models/mlflow-runs/$BUILD_ID/"
          },
          "performance_metrics": {
            "accuracy": $$ACC,
            "recall": $$REC,
            "precision": $$PREC,
            "f1_score": $$F1,
            "roc_auc": $$AUC
          },
          "training_config": {
            "framework": "tensorflow-keras",
            "federated_framework": "flower",
            "hospitals": ["hospital_a", "hospital_b", "hospital_c"],
            "num_rounds": 15,
            "local_epochs": 5,
            "batch_size": 64
          }
        }
        EOF
        
        echo ""
        echo "Model Registry Entry:"
        cat model_card.json
        echo ""
        
        # Upload to model registry in GCS
        gsutil cp model_card.json \
          gs://himas-mlops-models/model-registry/$${TIMESTAMP}_$BUILD_ID.json
        
        # Update latest pointer
        echo "$${TIMESTAMP}_$BUILD_ID" > latest_model.txt
        gsutil cp latest_model.txt gs://himas-mlops-models/model-registry/latest.txt
        
        echo ""
        echo "✅ Model registered in Model Registry (GCS-based)"
        echo "   Registry Entry: gs://himas-mlops-models/model-registry/$${TIMESTAMP}_$BUILD_ID.json"
        echo "   Model Artifact: gs://himas-mlops-models/models/$${TIMESTAMP}_$BUILD_ID/model.keras"
        echo "   Container Image: gcr.io/$PROJECT_ID/himas-training:$BUILD_ID"
        echo "   Latest Model: gs://himas-mlops-models/model-registry/latest.txt"

images:
  - 'gcr.io/$PROJECT_ID/himas-training:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/himas-training:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '3600s'